const SET_UID = "SET_UID";
const SET_AUTH_DATA = "SET_AUTH_DATA";
const SET_LOGIN_DETAILS = "SET_LOGIN_DETAILS";
const CLEAR_AUTH_DATA = "CLEAR_AUTH_DATA";
export { SET_UID, SET_AUTH_DATA, SET_LOGIN_DETAILS, CLEAR_AUTH_DATA };
